anchor_version = "0.24.2"
solana_version = "1.9.13"

[scripts]
test = "yarn mocha tests/*.spec.ts"

[provider]
cluster = "devnet"
wallet = "~/deployments/cryptocoders/cardinal/upgrade_authority.json"

[programs.mainnet]
cardinal_stake_pool = "GisLZe6PxAqovAo7SpKujhTk8J5Kd2kZYdEBWJaWU7me"
cardinal_reward_distributor = "CkyfuYw8x3YStMoxwKuSzo33czXL6r19xdQEwnvvxeZy"

[programs.devnet]
cardinal_stake_pool = "GisLZe6PxAqovAo7SpKujhTk8J5Kd2kZYdEBWJaWU7me"
cardinal_reward_distributor = "CkyfuYw8x3YStMoxwKuSzo33czXL6r19xdQEwnvvxeZy"

[programs.testnet]
cardinal_stake_pool = "GisLZe6PxAqovAo7SpKujhTk8J5Kd2kZYdEBWJaWU7me"
cardinal_reward_distributor = "CkyfuYw8x3YStMoxwKuSzo33czXL6r19xdQEwnvvxeZy"

[programs.localnet]
cardinal_stake_pool = "GisLZe6PxAqovAo7SpKujhTk8J5Kd2kZYdEBWJaWU7me"
cardinal_reward_distributor = "CkyfuYw8x3YStMoxwKuSzo33czXL6r19xdQEwnvvxeZy"
